import type { CompletedOrder, StoredUserState } from './types'

const daysAgo = (days: number, hour: number) => {
  const date = new Date()
  date.setDate(date.getDate() - days)
  date.setHours(hour, 20, 0, 0)
  return date.toISOString()
}

export const fallbackUser: StoredUserState = {
  authenticated: true,
  user: {
    id: 'usr-fathi-001',
    name: 'Fathi Abdat',
    email: 'fathi@example.com',
    phone: '+970 59 123 4567',
    savedAddress: {
      label: 'Home',
      fullName: 'Fathi Abdat',
      phone: '+970 59 123 4567',
      city: 'Ramallah',
      area: 'Al-Tireh',
      streetAddress: 'Al-Nahda Street',
      building: 'Building 12, Floor 3',
      postalCode: 'P600',
    },
  },
}

export const fallbackOrders: CompletedOrder[] = [
  {
    orderId: 'YTD-84291',
    userId: 'usr-fathi-001',
    restaurantId: 'rest-olive-kitchen',
    restaurantName: 'Olive Kitchen',
    items: [
      {
        id: 'meal-musakhan-rolls',
        restaurantId: 'rest-olive-kitchen',
        restaurantName: 'Olive Kitchen',
        name: 'Musakhan Rolls',
        description: 'Sumac chicken, caramelized onion, toasted taboon rolls',
        price: 28,
        image: '',
        category: 'Palestinian favorites',
        quantity: 2,
      },
      {
        id: 'meal-fattoush',
        restaurantId: 'rest-olive-kitchen',
        restaurantName: 'Olive Kitchen',
        name: 'Garden Fattoush',
        description: 'Crisp vegetables, herbs, toasted bread, pomegranate dressing',
        price: 18,
        image: '',
        category: 'Salads',
        quantity: 1,
      },
    ],
    shippingAddress: fallbackUser.user.savedAddress,
    deliveryMethod: 'asap',
    scheduledFor: null,
    estimatedDeliveryMinutes: 30,
    subtotal: 74,
    discount: 4,
    deliveryFee: 10,
    total: 80,
    currency: 'ILS',
    paymentMethod: 'digital-wallet',
    status: 'out-for-delivery',
    createdAt: daysAgo(0, 18),
  },
  {
    orderId: 'YTD-81647',
    userId: null,
    restaurantId: 'rest-saffron-table',
    restaurantName: 'Saffron Table',
    items: [
      {
        id: 'meal-maqluba',
        restaurantId: 'rest-saffron-table',
        restaurantName: 'Saffron Table',
        name: 'Chicken Maqluba',
        description: 'Layered spiced rice, vegetables, chicken, yogurt',
        price: 42,
        image: '',
        category: 'Rice dishes',
        quantity: 2,
      },
      {
        id: 'meal-knafeh',
        restaurantId: 'rest-saffron-table',
        restaurantName: 'Saffron Table',
        name: 'Nabulsi Knafeh',
        description: 'Crisp kataifi, Nabulsi cheese, orange blossom syrup',
        price: 22,
        image: '',
        category: 'Desserts',
        quantity: 1,
      },
    ],
    shippingAddress: {
      label: 'Other',
      fullName: 'Mira Saleh',
      phone: '+970 56 555 0142',
      city: 'Nablus',
      area: 'Rafidia',
      streetAddress: 'An-Najah Street',
      building: 'Near the cultural center',
    },
    deliveryMethod: 'scheduled',
    scheduledFor: daysAgo(5, 19),
    estimatedDeliveryMinutes: null,
    subtotal: 106,
    discount: 6,
    deliveryFee: 0,
    total: 100,
    currency: 'ILS',
    paymentMethod: 'cash',
    status: 'delivered',
    createdAt: daysAgo(6, 13),
  },
  {
    orderId: 'YTD-79102',
    userId: 'usr-fathi-001',
    restaurantId: 'rest-citrus-grill',
    restaurantName: 'Citrus Grill',
    items: [
      {
        id: 'meal-shish-tawook',
        restaurantId: 'rest-citrus-grill',
        restaurantName: 'Citrus Grill',
        name: 'Shish Tawook Plate',
        description: 'Chargrilled chicken, garlic sauce, pickles, warm pita',
        price: 38,
        image: '',
        category: 'From the grill',
        quantity: 1,
      },
    ],
    shippingAddress: fallbackUser.user.savedAddress,
    deliveryMethod: 'asap',
    scheduledFor: null,
    estimatedDeliveryMinutes: 25,
    subtotal: 38,
    discount: 0,
    deliveryFee: 10,
    total: 48,
    currency: 'ILS',
    paymentMethod: 'saved-card',
    status: 'cancelled',
    createdAt: daysAgo(14, 20),
  },
]
